### ISSUE TITLE
Cmake error after upgrade from Kubunutu 15.04 to 15.10

### ISSUE THREAD

**Issue by therob762** [bkloppenborg/simtoi#147]
The following is an error that I receive after completing an upgrade to Kubuntu 15.10.

-- Found Qt4: /usr/bin/qmake (found version "4.8.6") 
CMake Error at src/models/CMakeLists.txt:5 (INCLUDE):
  include could not find load file:

    ../

CMake Error at src/features/CMakeLists.txt:5 (INCLUDE):
  include could not find load file:

    ../

CMake Error at src/minimizers/CMakeLists.txt:5 (INCLUDE):
  include could not find load file:

    /home/therob/software/simtoi/src/minimizers/../

**Comment by bkloppenborg** [comment]
This is probably due to the version of CMake changing between Kubuntu versions rather than Kubuntu itself. I don't think the relative (`include(..)`) directives in `src/models/CMakeLists.txt:5` `src/features/CMakeLists.txt:5`, and `src/minimizers/CMakeLists.txt:5` are required anymore as the `src/CMakeLists.txt` includes its directory. Try removing the relative includes in the `CMakeLists.txt` files in the sub-directories.

**Comment by therob762** [comment]
That seemed to do the trick, but I have the following make error:

In file included from /home/therob/software/simtoi/lib/liboi/src/COpenCL.cpp:40:0:
/home/therob/software/simtoi/lib/liboi/src/COpenCL.hpp:72:22: fatal error: CL/cl.hpp: No such file or directory
compilation terminated.
lib/liboi/src/CMakeFiles/oi.dir/build.make:54: recipe for target 'lib/liboi/src/CMakeFiles/oi.dir/COpenCL.cpp.o' failed
make[2]: *** [lib/liboi/src/CMakeFiles/oi.dir/COpenCL.cpp.o] Error 1
CMakeFiles/Makefile2:674: recipe for target 'lib/liboi/src/CMakeFiles/oi.dir/all' failed
make[1]: *** [lib/liboi/src/CMakeFiles/oi.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

Should I put this as a separate issue?

**Comment by bkloppenborg** [comment]
RE: CMake changes:
Great! I'll make these modifications to the develop version and push changes later tonight.

RE: cl.hpp
Your OpenCL installation is missing the `cl.hpp` header file. This is a problem with your installation, not with SIMTOI. Ensure that the opencl-dev package installed cl.hpp. If not, you can grab a copy from Khronos and put it in the `/usr/include/CL/` directory manually.

**Comment by therob762** [comment]
Adding the cl.hpp file seemed to do the trick.
